version: "3"
services:
  easee2mqtt:
    build: ./
    restart: always
    networks:
      - network1
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - SETTINGS_FILE=/app/config/settings.json
networks:
  network1:
    name: mosquitto
    external: true
